version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Sscanf
        - os.Setenv
        - os.Unsetenv
        - os.RemoveAll
